SDSS-1302: Adding additional layout with widths baked in.
SU-SWS/ace-sdssgryphon pull request #453
Opened 2024-06-12 05:11 UTC by jenbreese

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? See [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2024-06-18 16:05 UTC, joegl requested changes
Everything looks good just a few small questions/requests. Tested it in Gitpod and works great 👍

2024-06-19 15:31 UTC, jenbreese commented on docroot/profiles/sdss/sdss_profile/config/sync/paragraphs.paragraphs_type.stanford_layout.yml
>        layout_paragraphs_sdss_2_column: '2 Column'
@joegl I wasn't sure about that. Will it cause problems for pages using the existing 50/50 layout?

2024-06-19 16:23 UTC, joegl commented on docroot/profiles/sdss/sdss_profile/config/sync/paragraphs.paragraphs_type.stanford_layout.yml
>        layout_paragraphs_sdss_2_column: '2 Column'
As long as we leave the machine name as `layout_paragraphs_sdss_2_column` and only change the 2 column label it should be fine.

2024-06-25 18:36 UTC, jenbreese commented on docroot/profiles/sdss/sdss_profile/config/sync/paragraphs.paragraphs_type.stanford_layout.yml
>        layout_paragraphs_sdss_2_column: '2 Column'
Hey @joegl Ok. This is the last comment to fix in this PR. I'll do this next.

2024-06-25 19:07 UTC, joegl commented on docroot/profiles/sdss/sdss_profile/config/sync/paragraphs.paragraphs_type.stanford_layout.yml
>        layout_paragraphs_sdss_2_column: '2 Column'
Awesome, thanks Jen! 👍

2024-06-25 21:41 UTC, jenbreese commented on docroot/profiles/sdss/sdss_profile/config/sync/paragraphs.paragraphs_type.stanford_layout.yml
>        layout_paragraphs_sdss_2_column: '2 Column'
Hi @joegl I double checked and this PR is ready for you to review the naming change requested above.

2024-07-01 16:55 UTC, joegl approved these changes
LGTM! Thanks Jen 👍

2024-07-01 16:56 UTC, merged